<div class="block-end">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('newproductslider/newproductslider')->setTemplate('magentothem/newproductslider/newproductslider.phtml')->toHtml(); ?>
	</div>
</div>
<div class="blog-slider">
	<div class="container">
		<?php  echo $this->getLayout()->createBlock('blog/menu_sidebar')->setTemplate('magentothem_blog/blog_slide.phtml')->toHtml(); ?>
	</div>
</div>


